### ISSUE TITLE
gfc-semver seems down

### ISSUE THREAD

**Issue by glebsts** [digital-preservation/csv-validator#126]
Hello,
Tried to add csv-validator-cmd 1.1.4 to my gradle file - failed with
```
Could not find com.gilt:gfc-semver_2.11:0.1.0.
Required by:
      :java-validator:unspecified > uk.gov.nationalarchives:csv-validator-cmd:1.1.4 > uk.gov.nationalarchives:csv-validator-core:1.1.4
```
Walked through different repos - same story. Not sure what should be fixed :) Asked in gilt gitter chat, but it is quiet.
Any advice? I have working package downloaded (that includes all libs) but would prefer not to keep it in repository.

**Comment by adamretter** [comment]
Seems to be available just fine for me from the repository described in the `pom.xml` or `csv-validator-core`, i.e.

```xml
<repository>
    <id>gilt-group</id>
    <name>Gilt Group Bintray Repo</name>
    <url>http://dl.bintray.com/giltgroupe/maven</url>
    <!-- needed for gfc-semver -->
</repository>
```

What seems to be the issue for you?

**Comment by glebsts** [comment]
Thank you, added this repo explicitly to gradle repo list, resolved. 
Unfortunately http://mvnrepository.com/artifact/uk.gov.nationalarchives/csv-validator-core/1.1.4 lists this dependency but does not provide it.

**Comment by adamretter** [comment]
@glebsts It is provided. We release to Maven Central, if you look at https://repo1.maven.org/maven2/uk/gov/nationalarchives/csv-validator-core/1.1.4/csv-validator-core-1.1.4.pom

You can clearly see the dependency declaration and also the repository declaration.

**Comment by glebsts** [comment]
Then gradle failed for me, sorry :)
Btw, it downloaded scala-parser-combinators_2.11-1.0.3.jar according to pom. Current cmd archive distibution includes scala-parser-combinators_2.11-1.0.1.jar, others same (exc scodec-bits_2.11-1.0.9, which seems ok). Calling validator with 1.0.3 lib caused
```
../java-validator/bin/validate tmp/report.csv ../schemas/report.csvs
Exception in thread "main" java.lang.NoClassDefFoundError: scala/util/parsing/combinator/RegexParsers
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at uk.gov.nationalarchives.csv.validator.cmd.CsvValidatorCmdApp$Config$.$lessinit$greater$default$7(CsvValidatorCmdApp.scala:50)
```
for me. Replaced this lib with 1.0.1 and works good. Didn't find anything in issue tracker :\
