### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by mhGLEIF** [digital-preservation/csv-validator#173]
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000012b79e027, pid=9777, tid=0x000000000000ea07
#

	at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$$anonfun$2.apply(CsvValidatorUi.scala:114)
	at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$$anonfun$2.apply(CsvValidatorUi.scala:114)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
# JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libawt_lwawt.dylib+0x1c027]  OGLSD_SetScratchSurface+0x49
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/michael.hopwood/hs_err_pid9777.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by mhGLEIF** [comment]
Here's another one. I think I broke the validator with the number of errors?

```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:200)
	at uk.gov.nationalarchives.csv.validator.cmd.CsvValidatorCmdApp$.validate(CsvValidatorCmdApp.scala:139)
	at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$.uk$gov$nationalarchives$csv$validator$ui$CsvValidatorUi$$validate(CsvValidatorUi.scala:130)
	at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$ContentPanel$$anonfun$5$$anonfun$apply$mcV$sp$5.apply(CsvValidatorUi.scala:285)
	at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$ContentPanel$$anonfun$5$$anonfun$apply$mcV$sp$5.apply(CsvValidatorUi.scala:285)
	at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$$anonfun$2.apply$mcV$sp(CsvValidatorUi.scala:114)
	at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$$anonfun$2.apply(CsvValidatorUi.scala:114)
	at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$$anonfun$2.apply(CsvValidatorUi.scala:114)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by DavidUnderdown** [comment]
Michael, as mentioned in the Validator documentation, you can assign more heap space to Java, see http://digital-preservation.github.io/csv-validator/#toc16.  I tend to copy the original .bat file, add in the max heap parameter and save the copy with -big-heap appended to the file name.

Now almost every system will be 64-bit we could perhaps have this set to a different value in the released batch/shell files, but if the system setting is higher that might possibly actually reduce the heap available to the validator.  32 bit Java is very restricted on the max heap.

**Comment by adamretter** [comment]
The SIGSEGV error will be a bug in the JVM itself or a memory problem on your system. Probably best to update to a newer JDK

**Comment by mhGLEIF** [comment]
Thanks @DavidUnderdown @adamretter I'll talk to my admins 😄
