### ISSUE TITLE
Getting java.lang.AbstractMethodError 

### ISSUE THREAD

**Issue by kulketan-cloud** [digital-preservation/csv-validator#319]
Hello,

I'm trying to use csv-validator but without success. 
Trying to use java-api as mentioned in docs

```
 Boolean failFast = false;
        List<Substitution> pathSubstitutions = new ArrayList<Substitution>();
        List<FailMessage> messages = CsvValidator.validate(path,"" +
                getServletContext().getRealPath("") +"bucketInfo.csvs",
                false,
                pathSubstitutions,
                false,
                false);
        if(messages.isEmpty()) {
            System.out.println("Completed validation OK");
        } else {
            for(FailMessage message : messages) {
                if(message instanceof WarningMessage) {
                    System.out.println("[WARN] " + message.getMessage());
                } else {
                    System.out.println("[ERROR] " + message.getMessage());
                }
            }
        }
```

**Error:**

```
java.lang.AbstractMethodError: uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anon$2.scala$util$parsing$combinator$Parsers$$lastNoSuccessVar()Lscala/util/DynamicVariable;
		at scala.util.parsing.combinator.Parsers$$anon$2.apply(Parsers.scala:881)
		at scala.util.parsing.combinator.PackratParsers$$anon$1.apply(PackratParsers.scala:110)
		at scala.util.parsing.combinator.RegexParsers$class.parse(RegexParsers.scala:149)
		at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anon$2.parse(CsvValidator.scala:32)
		at scala.util.parsing.combinator.RegexParsers$class.parseAll(RegexParsers.scala:165)
		at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anon$2.parseAll(CsvValidator.scala:32)
		at uk.gov.nationalarchives.csv.validator.schema.SchemaParser$class.parseSchemaVersion(SchemaParser.scala:141)
		at uk.gov.nationalarchives.csv.validator.schema.SchemaParser$class.parse(SchemaParser.scala:192)
		at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anon$2.parse(CsvValidator.scala:32)
		at uk.gov.nationalarchives.csv.validator.schema.SchemaParser$class.parseAndValidate(SchemaParser.scala:124)
		at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anon$2.parseAndValidate(CsvValidator.scala:32)
		at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anonfun$parseSchema$1.apply(CsvValidator.scala:74)
		at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anonfun$parseSchema$1.apply(CsvValidator.scala:73)
		at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:86)
		at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
		at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
		at scala.util.control.Exception$Catch.apply(Exception.scala:103)
		at scala.util.control.Exception$Catch.either(Exception.scala:125)
		at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:86)
		at resource.DeferredExtractableManagedResource.either(AbstractManagedResource.scala:29)
		at uk.gov.nationalarchives.csv.validator.MetaDataValidator$class.withReader(MetaDataValidator.scala:289)
		at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anon$2.withReader(CsvValidator.scala:32)
		at uk.gov.nationalarchives.csv.validator.api.CsvValidator$class.parseSchema(CsvValidator.scala:72)
		at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anon$2.parseSchema(CsvValidator.scala:32)
		at uk.gov.nationalarchives.csv.validator.api.java.CsvValidatorJavaBridge$.validate(CsvValidatorJavaBridge.scala:65)
		at uk.gov.nationalarchives.csv.validator.api.java.CsvValidatorJavaBridge$.validate(CsvValidatorJavaBridge.scala:30)
		at uk.gov.nationalarchives.csv.validator.api.java.CsvValidatorJavaBridge.validate(CsvValidatorJavaBridge.scala)
		at uk.gov.nationalarchives.csv.validator.api.java.CsvValidator.validate(CsvValidator.java:86)
		at uk.gov.nationalarchives.csv.validator.api.java.CsvValidator.validate(CsvValidator.java:67)
		at com.amazon.ijp_tool.servlets.IJPTeamView.validateBucketCSV(IJPTeamView.java:144)
		at com.amazon.ijp_tool.servlets.IJPTeamView.processCSV(IJPTeamView.java:117)
		at com.amazon.ijp_tool.servlets.IJPTeamView.doPost(IJPTeamView.java:66)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:880)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1601)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
```

**csvs file:**

```
version 1.1
@totalColumns 3
login: notEmpty
tm: notEmpty
bucket: is("1") or is("2") or is("3") or is("4") or is("NA") or is ("na")
```

**csv file:**
```
login,tm,bucket
ketan,ketantm,4
ketan,ketantm,2
ketan,ketantm,3
```

**Comment by DavidUnderdown** [comment]
Any suggestions @adamretter ?
